### ISSUE TITLE
Changing page into function 

### ISSUE THREAD

**Issue by PineAppleGrits** [eilex/discord.js-embed-menu#1]
Hello, I'm trying to change the page after executing a function using reactions. I didn't see a specific function to make it in the docs,  so i tried doing this. 
```javascript               
'3️⃣': async(menu) => {
                  //Code here
                  menu.setPage(0)
                  menu.clearReactions()
                  menu.addReactions()
                }
                
```
My question is, is this the right way? Because sometimes it freezes. And Also it's giving me this error: 

```sh
2021-06-13T23:30:10.858651+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'users' of undefined
2021-06-13T23:30:10.858654+00:00 app[worker.1]:     at ReactionCollector.<anonymous> (/app/node_modules/discord.js-embed-menu/dist/discord_embed_menu.js:148:49)
2021-06-13T23:30:10.858658+00:00 app[worker.1]:     at ReactionCollector.emit (events.js:388:22)
2021-06-13T23:30:10.858659+00:00 app[worker.1]:     at ReactionCollector.stop (/app/node_modules/discord.js/src/structures/interfaces/Collector.js:188:10)
2021-06-13T23:30:10.858660+00:00 app[worker.1]:     at DiscordEmbedMenu.stopReactions (/app/node_modules/discord.js-embed-menu/dist/discord_embed_menu.js:131:36)
2021-06-13T23:30:10.858661+00:00 app[worker.1]:     at DiscordEmbedMenu.setPage (/app/node_modules/discord.js-embed-menu/dist/discord_embed_menu.js:111:14)
2021-06-13T23:30:10.858661+00:00 app[worker.1]:     at processTicksAndRejections (internal/process/task_queues.js:95:5)
2021-06-13T23:30:10.858838+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

By the way, you can check the code in my github repo: https://github.com/PineAppleGrits/BHL/blob/dev-0.1/commands/moderation/ban.js

**Comment by PineAppleGrits** [comment]
By the way, i added clearReactions and AddReactions because if i dont add the first one it just adds reactions over the old ones, and the second one is because if i dont, it just doesnt add them

**Comment by ezequieljpereiraa** [comment]
@eilex Hi, I have the same question. Can you help us please?

**Comment by eilex** [comment]
Sorry for beign late @PineAppleGrits, with the latest version i've just uploaded (1.0.2) you can pass the name of the page to the "setPage" method.

In your case could be per example:
`
'3️⃣': async(menu) => {
  menu.setPage('sub-menu');  
}
`

There is no need to call "clearReactions" or "addReactions", it's already done by "setPage".

**Comment by ezequieljpereiraa** [comment]
> Sorry for beign late @PineAppleGrits, with the latest version i've just uploaded (1.0.2) you can pass the name of the page to the "setPage" method.
> 
> In your case could be per example:
> `'3️⃣': async(menu) => { menu.setPage('sub-menu'); }`
> 
> There is no need to call "clearReactions" or "addReactions", it's already done by "setPage".

Hi Eilex, thanks for the update. The setpage using the name works, but reactions are not removed. It only works when I put "menu.clearReactions()" after menu.setPage('name-here').  But if I put **"menu.clear Reactions()"**, sometimes it freezes and gives this error `(node:16420) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'users' of undefined`

**Embed without the "menu.clearReactions()" before click in reaction:**

![image](https://user-images.githubusercontent.com/67354756/124396312-2286a800-dcdf-11eb-8803-2ef80b617f3e.png)

**After click in reaction:**
![image](https://user-images.githubusercontent.com/67354756/124396397-a5a7fe00-dcdf-11eb-95e1-946db650900a.png)

Can you help me, please?

**Comment by eilex** [comment]
Thank you @mrsolarius, didn't see that :S

**Comment by mrsolarius** [comment]
You're welcome ;)
Lot of try to found the origin of that bug ^^
